apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-volume-pv
spec:
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data
  storageClassName: standard
  volumeMode: Filesystem
  capacity:
    storage: 1Gi